Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty32"

  config.vm.network "forwarded_port", guest: 8000, host: 8000

  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.synced_folder "..", "/vagrant", create: true

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "playbook.yml"
  end
end